In [8]:
import numpy as np

# DataTypes & Attributes

## Numpy's main dataype is `ndarray`

In [18]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [19]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape, a2.shape, a3.shape

((3,), (3, 3), (2, 3, 3))

In [22]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)